"""Source authority tiers for weighting headline signal.

Tier 1 (trusted): major global newswires + serious regional press.
  Multiplied ×1.5 in notability ranking.

Tier 3 (content farms / PR wires / low-quality republishers): ×0.4.

Tier 2 (default — legitimate trade press, mid-tier outlets): ×1.0.

Matching is case-insensitive substring against both the headline's
`source` name and its `link` URL. First match wins.
"""

TIER_1_PATTERNS = [
    # Global business / tech / financial
    "reuters", "bloomberg", "financial times", "ft.com",
    "wall street journal", "wsj.com", "new york times", "nytimes.com",
    "washington post", "associated press", "apnews.com", "ap news",
    "axios", "cnbc.com", "the economist", "economist.com",
    "techcrunch", "sifted", "the information", "theinformation.com",
    "wired", "forbes", "fortune", "business insider",
    "the verge", "ars technica", "bbc.com", "bbc.co.uk",
    "restofworld.org", "rest of world",
    "pitchbook", "crunchbase news", "strictlyvc",
    "semafor", "the atlantic",

    # Brazil / LatAm
    "valor econômico", "valor internacional", "valor international",
    "valor.globo", "folha de s.paulo", "folha de são paulo",
    "folha.uol", "estadão", "estadao.com",
    "brazil journal", "braziljournal",
    "neofeed", "pipeline valor", "pipelinevalor",
    "latamlist", "contxto", "bloomberg línea", "bloomberglinea",
    "exame.com", "istoédinheiro", "istoedinheiro", "o globo", "oglobo",

    # India
    "economic times", "livemint", "mint.com",
    "hindubusinessline", "hindu businessline", "moneycontrol",
    "business standard", "the hindu", "thehindu.com",
    "the ken", "the-ken", "inc42", "entrackr",
    "yourstory", "bloombergquint", "bq prime",

    # MENA / GCC
    "arabian business", "wamda", "menabytes", "gulf news",
    "the national news", "thenationalnews",

    # Australia / NZ
    "australian financial review", "afr.com",
    "the australian", "smh.com", "sydney morning herald",
    "the age",

    # SE Asia
    "nikkei asia", "asia.nikkei", "straits times",
    "tech in asia", "techinasia", "kr-asia", "kr asia", "krasia",
    "dealstreetasia", "deal street asia",

    # EU
    "le monde", "handelsblatt", "der spiegel", "spiegel.de",
    "el país", "elpais", "les echos", "lesechos",
    "financial news", "manager magazin",
]

TIER_3_PATTERNS = [
    # PR wires — republished press releases, not journalism
    "prnewswire", "pr newswire",
    "einpresswire", "ein presswire",
    "businesswire", "business wire",
    "globenewswire", "globe newswire",
    "prweb", "pr web",
    "news direct",
    "accesswire",

    # SEO / content-farm / autogenerated republishers we've observed
    "passionate in marketing",
    "businessnewsthisweek",
    "world.infonasional",
    "infonasional",
    "scanx.trad", "scanx.trade",
    "garh.in", "garh news",
    "tipranks",

    # Aggregators / blogs (often unattributed reposts)
    "medium.com",
    "blogspot",
    "wordpress.com",
    "substack.com",  # mixed quality, deranked by default
]


def tier_for(source, link=""):
    """Return 1 / 2 / 3 for a headline based on its source + link."""
    s = (source or "").lower()
    l = (link or "").lower()
    text = s + " " + l
    for p in TIER_1_PATTERNS:
        if p in text:
            return 1
    for p in TIER_3_PATTERNS:
        if p in text:
            return 3
    return 2


TIER_WEIGHT = {1: 1.5, 2: 1.0, 3: 0.4}
TIER_LABEL = {1: "trusted", 2: "standard", 3: "low"}
